// Base fictícia para testes do projeto Problema X Solução.
// Nenhuma ocorrência, loja, pessoa ou credencial abaixo é real.
const dados = [
  {categoria:`Caixas`,problema:`Caixa não inicia o sistema de vendas`,sintoma:`Ao ligar o terminal, a tela permanece carregando e o aplicativo de vendas não abre.`,solucao:`1. Confirme se o terminal está conectado à rede.\n2. Reinicie o equipamento.\n3. Abra novamente o sistema de vendas.\n4. Se persistir, registre o horário e encaminhe ao suporte.`,comando:``,observacao:`Não desligue o terminal durante uma atualização.`,tags:`caixa pdv inicializacao vendas terminal`},
  {categoria:`Caixas`,problema:`Leitor de código de barras não reconhece produtos`,sintoma:`O leitor acende, mas nenhum código é inserido no caixa.`,solucao:`1. Reconecte o cabo USB.\n2. Teste outra porta disponível.\n3. Leia um código de teste.\n4. Reinicie o caixa caso o leitor continue sem resposta.`,comando:``,observacao:`Teste com mais de uma etiqueta antes de concluir que o leitor falhou.`,tags:`caixa leitor codigo barras usb produto`},
  {categoria:`Caixas`,problema:`Pagamento por cartão fica processando`,sintoma:`A operação permanece em processamento e não apresenta aprovação ou recusa.`,solucao:`1. Verifique a conexão do terminal de pagamento.\n2. Aguarde o tempo limite da transação.\n3. Consulte se houve confirmação antes de tentar novamente.\n4. Reinicie somente o terminal de pagamento.`,comando:``,observacao:`Nunca repita a cobrança sem confirmar a situação da primeira tentativa.`,tags:`caixa cartao pagamento transacao pinpad`},
  {categoria:`Caixas`,problema:`Gaveta de dinheiro não abre`,sintoma:`A venda é concluída, mas a gaveta não destrava automaticamente.`,solucao:`1. Confira o cabo entre a gaveta e a impressora do caixa.\n2. Verifique se existe papel e se a impressora está ligada.\n3. Faça uma abertura de teste autorizada.`,comando:``,observacao:`A abertura manual deve seguir o procedimento interno da loja.`,tags:`caixa gaveta dinheiro impressora abertura`},
  {categoria:`Trocas`,problema:`Sistema não localiza o cupom para troca`,sintoma:`O número do cupom é informado, porém a venda original não aparece.`,solucao:`1. Confira todos os números do cupom.\n2. Valide a data e a loja de origem.\n3. Atualize a consulta.\n4. Se a venda for de outra unidade, siga o fluxo específico de troca.`,comando:``,observacao:`Ocorrência fictícia para treinamento.`,tags:`troca cupom venda consulta loja`},
  {categoria:`Trocas`,problema:`Produto aparece como não elegível para troca`,sintoma:`O item é encontrado, mas o sistema bloqueia a continuação do processo.`,solucao:`1. Verifique o prazo fictício da compra.\n2. Confira a condição e a categoria do item.\n3. Consulte as regras exibidas pelo sistema.\n4. Solicite autorização quando prevista.`,comando:``,observacao:`Não contém regras comerciais reais.`,tags:`troca produto bloqueio prazo elegibilidade`},
  {categoria:`Trocas`,problema:`Vale-troca não é gerado`,sintoma:`A troca é finalizada, porém o comprovante ou código do vale não aparece.`,solucao:`1. Confirme se o processo foi concluído.\n2. Verifique a impressora.\n3. Consulte o histórico da operação.\n4. Gere a segunda via pelo procedimento de teste.`,comando:``,observacao:`Evite refazer a troca antes de consultar o histórico.`,tags:`troca vale comprovante codigo segunda-via`},
  {categoria:`Sistemas Web`,problema:`Portal interno apresenta página em branco`,sintoma:`Após o login, o navegador abre uma página vazia sem menus.`,solucao:`1. Atualize a página.\n2. Abra uma janela privativa.\n3. Limpe somente os dados do site de teste.\n4. Teste outro navegador homologado.`,comando:``,observacao:`Não apague senhas ou dados pessoais do navegador.`,tags:`sistema web portal pagina branco navegador`},
  {categoria:`Sistemas Web`,problema:`Sessão expira logo após o acesso`,sintoma:`O usuário entra no portal e retorna imediatamente para a tela de login.`,solucao:`1. Confira data e hora do computador.\n2. Feche todas as abas do portal.\n3. Acesse novamente.\n4. Caso persista, valide a permissão do usuário.`,comando:``,observacao:`Use somente contas fictícias durante testes.`,tags:`sistema web sessao login expira acesso`},
  {categoria:`Sistemas Web`,problema:`Relatório não carrega`,sintoma:`Ao solicitar o relatório, o indicador de carregamento não termina.`,solucao:`1. Reduza o período da consulta.\n2. Remova filtros desnecessários.\n3. Atualize a página.\n4. Tente exportar novamente.`,comando:``,observacao:`Consultas extensas podem levar mais tempo.`,tags:`sistema web relatorio consulta carregamento exportar`},
  {categoria:`Depósito`,problema:`Coletor não sincroniza o inventário`,sintoma:`A contagem fica salva no aparelho, mas não aparece no sistema.`,solucao:`1. Verifique o Wi-Fi do depósito.\n2. Confirme se a tarefa está finalizada.\n3. Execute a sincronização novamente.\n4. Mantenha o coletor ligado até concluir.`,comando:``,observacao:`Não apague a tarefa antes de confirmar a sincronização.`,tags:`deposito coletor inventario sincronizacao wifi`},
  {categoria:`Depósito`,problema:`Etiqueta de recebimento não é impressa`,sintoma:`O recebimento é confirmado, mas a etiqueta não sai na impressora.`,solucao:`1. Verifique papel e energia.\n2. Confirme a impressora selecionada.\n3. Consulte a fila.\n4. Solicite a reimpressão da etiqueta.`,comando:``,observacao:`Confira se a etiqueta já não foi impressa em outro equipamento.`,tags:`deposito etiqueta recebimento impressora fila`},
  {categoria:`Depósito`,problema:`Produto recebido não aparece no estoque`,sintoma:`O recebimento foi finalizado, mas a quantidade não foi atualizada na consulta.`,solucao:`1. Atualize a tela de estoque.\n2. Confira o status do recebimento.\n3. Consulte possíveis pendências.\n4. Aguarde a sincronização e consulte novamente.`,comando:``,observacao:`Dados totalmente fictícios.`,tags:`deposito produto recebimento estoque quantidade`},
  {categoria:`Impressoras`,problema:`Impressora do caixa está offline`,sintoma:`O equipamento está ligado, mas aparece indisponível no sistema.`,solucao:`1. Verifique os cabos de energia e dados.\n2. Confirme se há luz de erro.\n3. Desligue e ligue a impressora.\n4. Atualize a fila de impressão.`,comando:``,observacao:`Não force a tampa ou o mecanismo de corte.`,tags:`impressoras caixa offline cabo fila`},
  {categoria:`Impressoras`,problema:`Cupom sai com impressão fraca`,sintoma:`As informações do cupom ficam claras ou parcialmente ilegíveis.`,solucao:`1. Confirme o lado correto do papel térmico.\n2. Limpe a área de impressão conforme o procedimento.\n3. Troque a bobina para teste.`,comando:``,observacao:`Aguarde o equipamento esfriar antes de qualquer limpeza.`,tags:`impressoras cupom fraco papel termico bobina`},
  {categoria:`Impressoras`,problema:`Documento fica preso na fila de impressão`,sintoma:`Novos documentos não imprimem porque existe um item parado na fila.`,solucao:`1. Abra a fila de impressão.\n2. Cancele o item com falha.\n3. Desligue e ligue a impressora.\n4. Envie uma página de teste.`,comando:``,observacao:`Confirme antes de cancelar documentos de outro usuário.`,tags:`impressoras documento fila preso cancelar`},
  {categoria:`RFID`,problema:`Leitor RFID não identifica a etiqueta`,sintoma:`O item está próximo ao leitor, mas nenhum código é reconhecido.`,solucao:`1. Verifique se a etiqueta está íntegra.\n2. Afaste outros itens.\n3. Reinicie a leitura.\n4. Teste uma etiqueta fictícia conhecida.`,comando:``,observacao:`Mantenha objetos metálicos afastados durante o teste.`,tags:`rfid leitor etiqueta identificacao item`},
  {categoria:`RFID`,problema:`Contagem RFID apresenta itens duplicados`,sintoma:`A mesma referência aparece mais de uma vez no resultado da leitura.`,solucao:`1. Encerre a leitura atual.\n2. Afaste itens da área já conferida.\n3. Inicie uma nova sessão.\n4. Compare o resultado com a lista de teste.`,comando:``,observacao:`Ocorrência criada apenas para demonstração.`,tags:`rfid contagem duplicado inventario leitura`},
  {categoria:`RFID`,problema:`Antena RFID aparece desconectada`,sintoma:`O painel indica que uma das antenas não está disponível.`,solucao:`1. Confira a energia do equipamento.\n2. Verifique visualmente os cabos.\n3. Reinicie o controlador.\n4. Consulte novamente o estado das antenas.`,comando:``,observacao:`Não desconecte cabos com o equipamento energizado.`,tags:`rfid antena desconectada cabo controlador`},
  {categoria:`Mobile`,problema:`Aplicativo da loja fecha sozinho`,sintoma:`O aplicativo encerra ao abrir uma função específica.`,solucao:`1. Feche o aplicativo completamente.\n2. Verifique espaço disponível.\n3. Reinicie o aparelho.\n4. Confira se existe atualização homologada.`,comando:``,observacao:`Não reinstale antes de confirmar se há dados pendentes.`,tags:`mobile aplicativo fecha celular atualizacao`},
  {categoria:`Mobile`,problema:`Celular corporativo não conecta ao Wi-Fi`,sintoma:`A rede aparece na lista, mas a conexão não é concluída.`,solucao:`1. Ative e desative o Wi-Fi.\n2. Esqueça a rede de teste.\n3. Conecte novamente.\n4. Reinicie o aparelho se necessário.`,comando:``,observacao:`Não registre credenciais reais na base.`,tags:`mobile celular wifi rede conexao`},
  {categoria:`Mobile`,problema:`Câmera não lê o código do produto`,sintoma:`A imagem abre, mas o aplicativo não reconhece o código.`,solucao:`1. Limpe a lente.\n2. Melhore a iluminação.\n3. Centralize o código.\n4. Teste outro produto fictício.`,comando:``,observacao:`Evite apontar a câmera diretamente para luz intensa.`,tags:`mobile camera codigo produto leitura`},
  {categoria:`Permissões`,problema:`Usuário não consegue acessar o relatório`,sintoma:`O menu do relatório não aparece ou informa acesso negado.`,solucao:`1. Confirme o perfil necessário.\n2. Verifique se o usuário está ativo.\n3. Solicite a permissão pelo fluxo de teste.\n4. Saia e entre novamente após a liberação.`,comando:``,observacao:`Permissões devem seguir aprovação interna.`,tags:`permissoes usuario relatorio acesso perfil`},
  {categoria:`Permissões`,problema:`Funcionário não pode cancelar uma operação`,sintoma:`O botão de cancelamento está desabilitado para o perfil atual.`,solucao:`1. Confirme se a função exige autorização.\n2. Verifique o perfil do usuário.\n3. Solicite apoio de um perfil autorizado.`,comando:``,observacao:`Não compartilhe usuários ou senhas.`,tags:`permissoes cancelamento operacao autorizacao perfil`},
  {categoria:`Permissões`,problema:`Novo usuário não aparece no sistema`,sintoma:`O cadastro foi solicitado, mas o usuário ainda não consegue entrar.`,solucao:`1. Confirme se a solicitação foi aprovada.\n2. Verifique a data de ativação.\n3. Atualize a consulta de usuários.\n4. Oriente uma nova tentativa de acesso.`,comando:``,observacao:`Use identificadores fictícios neste ambiente.`,tags:`permissoes novo usuario cadastro ativacao login`}
];
